# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-03 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestmatch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonFemale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('stud_id', models.CharField(max_length=10)),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonMale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('stud_id', models.CharField(max_length=10)),
                ('rating', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
