# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestmatch', '0002_auto_20170703_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('sex', models.CharField(max_length=1)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=None)),
                ('stud_id', models.CharField(max_length=10)),
                ('rating', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='PersonFemale',
        ),
        migrations.DeleteModel(
            name='PersonMale',
        ),
    ]
