# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 12:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bestmatch', '0003_auto_20170704_1027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='firstName',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='lastName',
        ),
    ]
