# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestmatch', '0004_auto_20170704_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='rated_num',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=1000000),
        ),
        migrations.AlterField(
            model_name='person',
            name='rating',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
    ]
