# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 12:08
from __future__ import unicode_literals

from django.db import migrations

import os
from os import listdir
from os.path import isfile, join
from bestmatch.models import Person

def forwards(apps, schema_editor):
    if not schema_editor.connection.alias == 'default':
        return

    sex = 'F'
    path = 'staticfiles/bestmatch/images/' + sex

    for f in listdir(path):
        if isfile(join(path, f)):
            idx, name = f.split('_', 1)
            name = name.replace('_', ' ')
            photo = sex + '/' + f
            rating = 5.0

            p = Person(name=name, sex=sex, photo=f, stud_id=idx, rating=rating)
            p.save()

    sex = 'M'
    path = 'staticfiles/bestmatch/images/' + sex

    for f in listdir(path):
        if isfile(join(path, f)):
            idx, name = f.split('_', 1)
            name.replace('_', ' ')
            photo = sex + '/' + f
            rating = 5.0
            p = Person(name=name, sex=sex, photo=f, stud_id=idx, rating=rating)
            p.save()

class Migration(migrations.Migration):

    dependencies = [
        ('bestmatch', '0005_auto_20170807_1253'),
    ]

    operations = [
        migrations.RunPython(forwards)
    ]
