# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_modified', models.CharField(max_length=50)),
            ],
        ),
    ]
