# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 08:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbr', models.CharField(max_length=50, verbose_name='Course Abbr')),
                ('title', models.CharField(max_length=50, verbose_name='Course Title')),
                ('credits', models.FloatField(default=3.0, max_length=20, verbose_name='Cr(US)')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.School')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=10)),
                ('days', models.CharField(max_length=10)),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('faculty', models.CharField(max_length=50)),
                ('room', models.CharField(max_length=50)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Subject')),
            ],
        ),
    ]
