# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_subject_subjectinstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectinstance',
            name='endTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='subjectinstance',
            name='startTime',
            field=models.DateTimeField(),
        ),
    ]
