# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20170804_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashcode', models.CharField(max_length=50)),
                ('created', models.DateTimeField()),
                ('courses', models.CharField(max_length=200)),
            ],
        ),
    ]
