# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='numOfTables',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='session',
            name='tables',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session',
            name='courses',
            field=models.TextField(),
        ),
    ]
